version: '2.0'
services:
  redis:
    image: redis:alpine
    container_name: pimcore-redis

  db:
    image: mariadb:10.1
    container_name: pimcore-mariadb
    working_dir: /application
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - pimcore-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore
      
  php:
    image: dpfaffenbauer/pimcore-docker-php-fpm:PHP7-apache
# for PHP7.1 use: dpfaffenbauer/pimcore-docker-php-fpm:PHP7.1-apache
    container_name: pimcore-php-fpm
    volumes:
      - .:/var/www/html:cached
      - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    ports:
      - "2000:80"
    links:
     - db:db
     - redis:redis

volumes:
  pimcore-database: