db:
    # The type of your service (mariadb), which uses the format
    # 'type:version'. Be sure to consult the MariaDB/MySQL documentation
    # (https://docs.platform.sh/add-services/mysql.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: mariadb:10.6
    # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
    disk: 2048

# The name given to the Redis service (lowercase alphanumeric only).
cacheredis:
    # The type of your service (redis), which uses the format
    # 'type:version'. Be sure to consult the Redis documentation
    # (https://docs.platform.sh/add-services/redis.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: redis:7.0